/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    DemoBlock: typeof import('./../components/DemoBlock.vue')['default']
    GlobalDialog: typeof import('./../components/GlobalDialog.vue')['default']
    GlobalLoading: typeof import('./../components/GlobalLoading.vue')['default']
    GlobalToast: typeof import('./../components/GlobalToast.vue')['default']
    PrivacyPopup: typeof import('./../components/PrivacyPopup.vue')['default']
    UniEcharts: typeof import('uni-echarts')['default']
    WdActionSheet: typeof import('@wot-ui/ui/components/wd-action-sheet/wd-action-sheet.vue')['default']
    WdBadge: typeof import('@wot-ui/ui/components/wd-badge/wd-badge.vue')['default']
    WdButton: typeof import('@wot-ui/ui/components/wd-button/wd-button.vue')['default']
    WdCell: typeof import('@wot-ui/ui/components/wd-cell/wd-cell.vue')['default']
    WdCellGroup: typeof import('@wot-ui/ui/components/wd-cell-group/wd-cell-group.vue')['default']
    WdConfigProvider: typeof import('@wot-ui/ui/components/wd-config-provider/wd-config-provider.vue')['default']
    WdDatetimePicker: typeof import('@wot-ui/ui/components/wd-datetime-picker/wd-datetime-picker.vue')['default']
    WdDialog: typeof import('@wot-ui/ui/components/wd-dialog/wd-dialog.vue')['default']
    WdFormItem: typeof import('@wot-ui/ui/components/wd-form-item/wd-form-item.vue')['default']
    WdGap: typeof import('@wot-ui/ui/components/wd-gap/wd-gap.vue')['default']
    WdIcon: typeof import('@wot-ui/ui/components/wd-icon/wd-icon.vue')['default']
    WdInput: typeof import('@wot-ui/ui/components/wd-input/wd-input.vue')['default']
    WdLoading: typeof import('@wot-ui/ui/components/wd-loading/wd-loading.vue')['default']
    WdNotify: typeof import('@wot-ui/ui/components/wd-notify/wd-notify.vue')['default']
    WdPicker: typeof import('@wot-ui/ui/components/wd-picker/wd-picker.vue')['default']
    WdPopup: typeof import('@wot-ui/ui/components/wd-popup/wd-popup.vue')['default']
    WdSearch: typeof import('@wot-ui/ui/components/wd-search/wd-search.vue')['default']
    WdStep: typeof import('@wot-ui/ui/components/wd-step/wd-step.vue')['default']
    WdSteps: typeof import('@wot-ui/ui/components/wd-steps/wd-steps.vue')['default']
    WdSwitch: typeof import('@wot-ui/ui/components/wd-switch/wd-switch.vue')['default']
    WdTab: typeof import('@wot-ui/ui/components/wd-tab/wd-tab.vue')['default']
    WdTabbar: typeof import('@wot-ui/ui/components/wd-tabbar/wd-tabbar.vue')['default']
    WdTabbarItem: typeof import('@wot-ui/ui/components/wd-tabbar-item/wd-tabbar-item.vue')['default']
    WdTabs: typeof import('@wot-ui/ui/components/wd-tabs/wd-tabs.vue')['default']
    WdTextarea: typeof import('@wot-ui/ui/components/wd-textarea/wd-textarea.vue')['default']
    WdToast: typeof import('@wot-ui/ui/components/wd-toast/wd-toast.vue')['default']
    WdUpload: typeof import('@wot-ui/ui/components/wd-upload/wd-upload.vue')['default']
  }
}
